TOP30_FULL = [
    "usa_combustible_limpio",
    "usa_combustible_precario",
    "dispositivo_servicio_digital_2",
    "material_techo",
    "nivel_educativo_jefe_ord",
    "dispositivo_servicio_digital_3",
    "piso_precario",
    "ingreso_neto_total_hogar",
    "num_habitaciones",
    "acceso_internet_hogar_derivado",
    "dispositivo_servicio_digital_1",
    "material_pared",
    "tam_hogar",
    "num_ninos_0_5",
    "num_ninos_6_16",
    "num_miembros_afiliados_essalud",
    "estrato_geografico",
    "monto_juntos",
    "acceso_desague_red",
    "monto_bono_gas",
    "monto_pension_65",
    "num_miembros_sin_atencion_salud",
    "acceso_agua_red",
    "num_miembros_con_enfermedad_4_sem",
    "monto_programa_contigo",
    "agua_potable_reportada",
    "tipo_vivienda",
    "monto_otras_transferencias_publicas",
    "monto_bono_electricidad",
    "num_miembros_con_sintoma_4_sem",
]

FEATURE_CONFIG = {
    "usa_combustible_limpio": {
        "label": "El hogar usa combustible limpio para cocinar",
        "input_type": "selectbox",
        "display_map": {"No": 0, "Sí": 1},
    },
    "usa_combustible_precario": {
        "label": "El hogar usa combustible precario para cocinar",
        "input_type": "selectbox",
        "display_map": {"No": 0, "Sí": 1},
    },
    "dispositivo_servicio_digital_1": {
        "label": "Dispositivo o servicio digital 1",
        "input_type": "selectbox",
        "display_map": {"No": 0, "Sí": 1},
    },
    "dispositivo_servicio_digital_2": {
        "label": "Dispositivo o servicio digital 2",
        "input_type": "selectbox",
        "display_map": {"No": 0, "Sí": 1},
    },
    "dispositivo_servicio_digital_3": {
        "label": "Dispositivo o servicio digital 3",
        "input_type": "selectbox",
        "display_map": {"No": 0, "Sí": 1},
    },
    "material_techo": {
        "label": "Material predominante del techo",
        "input_type": "selectbox_dynamic",
    },
    "nivel_educativo_jefe_ord": {
        "label": "Nivel educativo del jefe del hogar",
        "input_type": "selectbox",
        "display_map": {
            "Sin nivel": 1,
            "Educación inicial": 2,
            "Primaria incompleta": 3,
            "Primaria completa": 4,
            "Secundaria incompleta": 5,
            "Secundaria completa": 6,
            "Superior no universitaria incompleta": 7,
            "Superior no universitaria completa": 8,
            "Superior universitaria incompleta": 9,
            "Superior universitaria completa": 10,
            "Maestría o doctorado": 11,
            "Básica especial": 12,
        },
    },
    "piso_precario": {
        "label": "El hogar tiene piso precario",
        "input_type": "selectbox",
        "display_map": {"No": 0, "Sí": 1},
    },
    "ingreso_neto_total_hogar": {
        "label": "Ingreso neto total del hogar",
        "input_type": "number_input",
        "min_value": 0.0,
        "step": 50.0,
        "format": "%.2f",
    },
    "num_habitaciones": {
        "label": "Número de habitaciones de la vivienda",
        "input_type": "number_input",
        "min_value": 0,
        "step": 1,
    },
    "acceso_internet_hogar_derivado": {
        "label": "El hogar tiene acceso a internet",
        "input_type": "selectbox",
        "display_map": {"No": 0, "Sí": 1},
    },
    "material_pared": {
        "label": "Material predominante de la pared",
        "input_type": "selectbox_dynamic",
    },
    "tam_hogar": {
        "label": "Tamaño del hogar",
        "input_type": "number_input",
        "min_value": 1,
        "step": 1,
    },
    "num_ninos_0_5": {
        "label": "Número de niños de 0 a 5 años",
        "input_type": "number_input",
        "min_value": 0,
        "step": 1,
    },
    "num_ninos_6_16": {
        "label": "Número de niños y adolescentes de 6 a 16 años",
        "input_type": "number_input",
        "min_value": 0,
        "step": 1,
    },
    "num_miembros_afiliados_essalud": {
        "label": "Número de miembros afiliados a EsSalud",
        "input_type": "number_input",
        "min_value": 0,
        "step": 1,
    },
    "estrato_geografico": {
        "label": "Estrato geográfico del hogar",
        "input_type": "selectbox_dynamic",
    },
    "monto_juntos": {
        "label": "Monto recibido del programa Juntos",
        "input_type": "number_input",
        "min_value": 0.0,
        "step": 50.0,
        "format": "%.2f",
    },
    "acceso_desague_red": {
        "label": "El hogar tiene acceso a desagüe por red pública",
        "input_type": "selectbox",
        "display_map": {"No": 0, "Sí": 1},
    },
    "monto_bono_gas": {
        "label": "Monto recibido por Bono del Gas",
        "input_type": "number_input",
        "min_value": 0.0,
        "step": 10.0,
        "format": "%.2f",
    },
    "monto_pension_65": {
        "label": "Monto recibido por Pensión 65",
        "input_type": "number_input",
        "min_value": 0.0,
        "step": 10.0,
        "format": "%.2f",
    },
    "num_miembros_sin_atencion_salud": {
        "label": "Número de miembros sin atención en salud",
        "input_type": "number_input",
        "min_value": 0,
        "step": 1,
    },
    "acceso_agua_red": {
        "label": "El hogar tiene acceso a agua por red pública",
        "input_type": "selectbox",
        "display_map": {"No": 0, "Sí": 1},
    },
    "num_miembros_con_enfermedad_4_sem": {
        "label": "Número de miembros con enfermedad en últimas 4 semanas",
        "input_type": "number_input",
        "min_value": 0,
        "step": 1,
    },
    "monto_programa_contigo": {
        "label": "Monto recibido por programa Contigo",
        "input_type": "number_input",
        "min_value": 0.0,
        "step": 10.0,
        "format": "%.2f",
    },
    "agua_potable_reportada": {
        "label": "El hogar reporta agua potable",
        "input_type": "selectbox",
        "display_map": {"No": 0, "Sí": 1},
    },
    "tipo_vivienda": {
        "label": "Tipo de vivienda",
        "input_type": "selectbox_dynamic",
    },
    "monto_otras_transferencias_publicas": {
        "label": "Monto por otras transferencias públicas",
        "input_type": "number_input",
        "min_value": 0.0,
        "step": 10.0,
        "format": "%.2f",
    },
    "monto_bono_electricidad": {
        "label": "Monto recibido por Bono Electricidad",
        "input_type": "number_input",
        "min_value": 0.0,
        "step": 10.0,
        "format": "%.2f",
    },
    "num_miembros_con_sintoma_4_sem": {
        "label": "Número de miembros con síntoma o malestar en últimas 4 semanas",
        "input_type": "number_input",
        "min_value": 0,
        "step": 1,
    },
}
